environment:
  name: prod
  project: cdf-bootcamp-18-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-18-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: ${CDF_URL}
      IDP_SCOPES: ${IDP_SCOPES}
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR TEST DATA DEVELOPER ENTRA GROUP
      data_developer_source_id: ${DATA_DEVELOPER_SOURCE_ID}
      # OBJECT ID FOR TEST DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: ${DATA_PIPELINE_OEE_SOURCE_ID}
      # OBJECT ID FOR TEST ADMIN TK ENTRA GROUP
      readwrite_source_id: ${READ_WRITE_SOURCE_ID}
      readonly_source_id: ${READ_ONLY_SOURCE_ID}
      # OBJECT ID FOR TEST ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: ${ICAPI_EXTRACTORS_SOURCE_ID}
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      
      icapi_ds_external_id: ds_icapi

      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee