name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build-and-dry-run:
    runs-on: ubuntu-latest
    env:
      GITHUB_ENV: test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: pipx install poetry==1.2.0
        
    - name: Build
      run: poetry run cdf-tk build --env=test

    - name: Dry run Deploy
      run: poetry run cdf-tk deploy --env=test --dry-run

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-dry-run]
    env:
      GITHUB_ENV: prod
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: pipx install poetry==1.2.0
        
    - name: Deploy
      run: poetry run cdf-tk deploy --env=prod

