name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build-and-dry-run:
    runs-on: ubuntu-latest
    environment: test
    env:
      GITHUB_ENV: test
      PYTHON_VERSION: '3.11'
      CDF_PROJECT: ${{ vars.CDF_PROJECT }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v5
      with:
          python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      run: pipx install poetry==1.8.0 --python ${{ env.PYTHON_VERSION }}

    - name: Setup Project
      run: poetry install
        
    - name: Build
      run: poetry run cdf-tk build --env=test

    - name: Dry run Deploy
      run: poetry run cdf-tk deploy --env=test --dry-run

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-dry-run]
    environment: prod
    env:
      PYTHON_VERSION: '3.11'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v5
      with:
          python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      run: pipx install poetry==1.8.0 --python ${{ env.PYTHON_VERSION }}

    - name: Setup Project
      run: poetry install
      
    - name: Deploy
      run: poetry run cdf-tk deploy --env=prod