name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, prod]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: pipx install poetry==1.2.0
        
    - name: Build
      run: poetry run cdf-tk build --env=${{ matrix.environment }}

    - name: Dry run Deploy
      run: poetry run cdf-tk deploy --env=${{ matrix.environment }} --dry-run
    
    - name: Deploy
      run: poetry run cdf-tk deploy --env=${{ matrix.environment }}

